# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY computer_mcp_server.py .

# Patch server to bind to 0.0.0.0 and use PORT env var
RUN sed -i 's/host="127.0.0.1"/host="0.0.0.0"/' computer_mcp_server.py \
    && sed -i 's/port=9000/port=port/' computer_mcp_server.py

# Expose port from environment
EXPOSE 9000

# Default command
CMD ["python", "computer_mcp_server.py"]
